
name: Build and deploy ASP.Net Core app to Azure Web App - api-portfolio-website

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  # Name of this job
  test:
# Which OS should this run on
    runs-on: windows-latest
    env:
      TestingDb : ${{ secrets.TestingDb }}
# The actual instruction you give the machine to execute
    steps:
    # download your source code- equivalent to your git clone command
    
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: 17
          distribution: 'zulu' # 
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v3
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner
    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      # the command below installs the correct sonarscanner variation for us. The command installs the app at the (relative) path given.
      run: |
        dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

# This regular dotnet CLI command will restore and build before testing.
# the additional commands: 
  # collect = the keyword to the test runner program that tells which test type to run.
  # logger = which logger to log the test results with:
  # Datacollection.... = the test  
    - name: Test
      run: dotnet test --verbosity normal --collect:"XPlat Code Coverage" --logger trx -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

# the scanner needs to 1)be started, 2)the app built, then 3)ended. The app must be built between the "begin" and "end" statements.
# The 1st arg, a path, is the path to the scanner .exe that we downloaded in the 'Install SonarCloud scanner' step above.
# The further args in the begin command communicate to sonarcloud the related organization and project, then the token they gave us so they can match them.
# The rest is where to store the test results and (most importantly) the files to exclude 
    - name: Build and analyze
      shell: powershell
      run: |
        .\.sonar\scanner\dotnet-sonarscanner begin /k:"markcmoore_portfolio-dotnet-webapi" /o:"markcmoore" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" /d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx" /d:sonar.coverage.exclusions="**/DB_OracleCreds/**/*.*"
        dotnet build --no-restore 
        .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
    - name: logout
      run: |
        az logout

  build:
      runs-on: windows-latest    
      steps:
        - uses: actions/checkout@v2
  
        - name: Set up .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '7.x'
            include-prerelease: true
            
        - name: Build with dotnet
          run: dotnet build ./portfolio_controllers/portfolio_website.csproj --configuration Release
  
        - name: dotnet publish
          run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp # this path is where the .exe of the api is stored
          
        - name: Upload artifact for deployment job
          uses: actions/upload-artifact@v2
          with:
            name: .net-app
            path: ${{env.DOTNET_ROOT}}/myapp # this step looks in that dir we just created and (probably) stores the reference in a variable called '.net-app' so that it can be retreived later.
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app # retrieving that .exe file and store it 
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'api-portfolio-website'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_55E462089B5C4DCCACD5F6FCC22F6FA2 }} # this secret is all Azure needs to find the correct resource.
          package: . # the location of the .exe. in this case, it's in the same dir.